name: Bug Report
description: Something is wrong with this package.
labels: [not confirmed]
assignees: Ferks-FK
body:
- type: textarea
  atributes:
    label: Current Behavior
    description: Provide a clean and concise description of the problem.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: Describe what you expect to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Provide the steps to reproduce the problem, if the problem cannot be reproduced, the problem will be closed.
  validations:
    required: true

- type: textarea
    attributes:
      label: System Information
      description: >
        Run `python -m control_wrapper -v` and paste this information below.
    validations:
      required: true

- type: checkboxes
    attributes:
      label: Checklist
      description: >
        Please, before you open this issue, be sure that this has not been reported before.
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
        - label: I have removed any sensitive if visible data (URL's and Tokens).
          required: true
