name: GitHub Pages

on:
  push:
    branches: [docs]
    paths: [docs/**]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Build Documentation
        working-directory: docs
        run: |
          yarn install
          yarn build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.ACCESSTOKEN }}
           publish_dir: ./build
           user_name: github-actions[bot]
           user_email: 41898282+github-actions[bot]@users.noreply.github.com